// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	"github.com/google/go-containerregistry/pkg/v1"
	"github.com/google/go-containerregistry/pkg/v1/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLayer creates a new instance of MockLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLayer {
	mock := &MockLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLayer is an autogenerated mock type for the Layer type
type MockLayer struct {
	mock.Mock
}

type MockLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLayer) EXPECT() *MockLayer_Expecter {
	return &MockLayer_Expecter{mock: &_m.Mock}
}

// Compressed provides a mock function for the type MockLayer
func (_mock *MockLayer) Compressed() (io.ReadCloser, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Compressed")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayer_Compressed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compressed'
type MockLayer_Compressed_Call struct {
	*mock.Call
}

// Compressed is a helper method to define mock.On call
func (_e *MockLayer_Expecter) Compressed() *MockLayer_Compressed_Call {
	return &MockLayer_Compressed_Call{Call: _e.mock.On("Compressed")}
}

func (_c *MockLayer_Compressed_Call) Run(run func()) *MockLayer_Compressed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLayer_Compressed_Call) Return(readCloser io.ReadCloser, err error) *MockLayer_Compressed_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockLayer_Compressed_Call) RunAndReturn(run func() (io.ReadCloser, error)) *MockLayer_Compressed_Call {
	_c.Call.Return(run)
	return _c
}

// DiffID provides a mock function for the type MockLayer
func (_mock *MockLayer) DiffID() (v1.Hash, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiffID")
	}

	var r0 v1.Hash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (v1.Hash, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() v1.Hash); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(v1.Hash)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayer_DiffID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiffID'
type MockLayer_DiffID_Call struct {
	*mock.Call
}

// DiffID is a helper method to define mock.On call
func (_e *MockLayer_Expecter) DiffID() *MockLayer_DiffID_Call {
	return &MockLayer_DiffID_Call{Call: _e.mock.On("DiffID")}
}

func (_c *MockLayer_DiffID_Call) Run(run func()) *MockLayer_DiffID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLayer_DiffID_Call) Return(hash v1.Hash, err error) *MockLayer_DiffID_Call {
	_c.Call.Return(hash, err)
	return _c
}

func (_c *MockLayer_DiffID_Call) RunAndReturn(run func() (v1.Hash, error)) *MockLayer_DiffID_Call {
	_c.Call.Return(run)
	return _c
}

// Digest provides a mock function for the type MockLayer
func (_mock *MockLayer) Digest() (v1.Hash, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Digest")
	}

	var r0 v1.Hash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (v1.Hash, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() v1.Hash); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(v1.Hash)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayer_Digest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Digest'
type MockLayer_Digest_Call struct {
	*mock.Call
}

// Digest is a helper method to define mock.On call
func (_e *MockLayer_Expecter) Digest() *MockLayer_Digest_Call {
	return &MockLayer_Digest_Call{Call: _e.mock.On("Digest")}
}

func (_c *MockLayer_Digest_Call) Run(run func()) *MockLayer_Digest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLayer_Digest_Call) Return(hash v1.Hash, err error) *MockLayer_Digest_Call {
	_c.Call.Return(hash, err)
	return _c
}

func (_c *MockLayer_Digest_Call) RunAndReturn(run func() (v1.Hash, error)) *MockLayer_Digest_Call {
	_c.Call.Return(run)
	return _c
}

// MediaType provides a mock function for the type MockLayer
func (_mock *MockLayer) MediaType() (types.MediaType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MediaType")
	}

	var r0 types.MediaType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (types.MediaType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() types.MediaType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(types.MediaType)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayer_MediaType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MediaType'
type MockLayer_MediaType_Call struct {
	*mock.Call
}

// MediaType is a helper method to define mock.On call
func (_e *MockLayer_Expecter) MediaType() *MockLayer_MediaType_Call {
	return &MockLayer_MediaType_Call{Call: _e.mock.On("MediaType")}
}

func (_c *MockLayer_MediaType_Call) Run(run func()) *MockLayer_MediaType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLayer_MediaType_Call) Return(mediaType types.MediaType, err error) *MockLayer_MediaType_Call {
	_c.Call.Return(mediaType, err)
	return _c
}

func (_c *MockLayer_MediaType_Call) RunAndReturn(run func() (types.MediaType, error)) *MockLayer_MediaType_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockLayer
func (_mock *MockLayer) Size() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayer_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockLayer_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockLayer_Expecter) Size() *MockLayer_Size_Call {
	return &MockLayer_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockLayer_Size_Call) Run(run func()) *MockLayer_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLayer_Size_Call) Return(n int64, err error) *MockLayer_Size_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLayer_Size_Call) RunAndReturn(run func() (int64, error)) *MockLayer_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Uncompressed provides a mock function for the type MockLayer
func (_mock *MockLayer) Uncompressed() (io.ReadCloser, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Uncompressed")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayer_Uncompressed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uncompressed'
type MockLayer_Uncompressed_Call struct {
	*mock.Call
}

// Uncompressed is a helper method to define mock.On call
func (_e *MockLayer_Expecter) Uncompressed() *MockLayer_Uncompressed_Call {
	return &MockLayer_Uncompressed_Call{Call: _e.mock.On("Uncompressed")}
}

func (_c *MockLayer_Uncompressed_Call) Run(run func()) *MockLayer_Uncompressed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLayer_Uncompressed_Call) Return(readCloser io.ReadCloser, err error) *MockLayer_Uncompressed_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockLayer_Uncompressed_Call) RunAndReturn(run func() (io.ReadCloser, error)) *MockLayer_Uncompressed_Call {
	_c.Call.Return(run)
	return _c
}
