# Default values for sbombastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# NOTE: This section is used to configure the global settings for the sbombastic chart.
global:
  cattle:
    systemDefaultRegistry: ghcr.io

controller:
  image:
    repository: rancher-sandbox/sbombastic/controller
    tag: v0.5.0
    pullPolicy: IfNotPresent
  replicas: 3
  logLevel: "info"
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 300Mi

storage:
  image:
    repository: rancher-sandbox/sbombastic/storage
    tag: v0.5.0
    pullPolicy: IfNotPresent
  replicas: 1
  # logLevel: "debug" //TODO: uncomment this, when the log parser in storage is implemented
  resources:
    limits:
      cpu: 500m
      memory: 3Gi
    requests:
      cpu: 250m
      memory: 300Mi

worker:
  image:
    repository: rancher-sandbox/sbombastic/worker
    tag: v0.5.0
    pullPolicy: IfNotPresent
  replicas: 3
  logLevel: "info"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 300Mi

persistence:
  enabled: true

  ## Specify a PVC for the storage data
  storageData:
    enabled: true
    subPath:
    annotations: {}
    labels: {}
    # storageClass: ""
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    accessMode: ReadWriteOnce
    size: 1Gi

# NOTE: This section is used to configure the NATS server and its components
# deployed by the NATS chart dependency.
# Do not edit this section manually.
nats:
  tlsCA:
    enabled: true
    secretName: sbombastic-nats-server-tls
  config:
    nats:
      tls:
        enabled: true
        secretName: sbombastic-nats-server-tls
        merge:
          verify: true
    cluster:
      enabled: true
      tls:
        enabled: true
        secretName: sbombastic-nats-routes-tls
    jetstream:
      enabled: true
  natsBox:
    enabled: false
  container:
    merge:
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
            type: RuntimeDefault
        allowPrivilegeEscalation: false
        capabilities:
            drop:
            - "ALL"
  reloader:
    merge:
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
            type: RuntimeDefault
        allowPrivilegeEscalation: false
        capabilities:
            drop:
            - "ALL"
