{{- if .Values.mcp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sbomscanner.fullname" . }}-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sbomscanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
spec:
  type: {{ .Values.mcp.service.type }}
  ports:
  - name: {{ if .Values.mcp.disableTLS }}http{{ else }}https{{ end }}
    port: {{ .Values.mcp.service.port }}
    targetPort: {{ .Values.mcp.service.port }}
    protocol: TCP
    {{- if eq .Values.mcp.service.type "NodePort" }}
    nodePort: {{ .Values.mcp.service.nodePort }}
    {{- end }}
  selector:
    {{- include "sbomscanner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
{{- end }}
