apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.storage.pvc.name}}
spec:
  storageClassName: {{ .Values.storage.storageClass.name }}
  accessModes:
    {{ .Values.storage.pvc.accessModes | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.requestStorage }}