apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClass.name }}
provisioner: {{ .Values.storage.storageClass.provisioner }}
allowVolumeExpansion: {{ .Values.storage.storageClass.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.storage.storageClass.volumeBindingMode }}
