apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbombastic.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" .| nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{ include "sbombastic.selectorLabels" .| nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{ include "sbombastic.labels" .| nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "sbombastic.fullname" . }}-worker
      containers:
        - name: worker
          image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
            - -nats-url
            - {{ .Release.Name }}-controller-nats.{{ .Release.Namespace }}.svc.cluster.local:4222
            {{- if .Values.worker.logLevel }}
            - -log-level={{ .Values.worker.logLevel }}
            {{- end }}
          volumeMounts:
            - mountPath: /var/run/worker
              name: run-volume
      volumes:
        - name: run-volume
          emptyDir: {}
