apiVersion: sbomscanner.kubewarden.io/v1alpha1
kind: Registry
metadata:
  name: my-first-registry
  namespace: default
spec:
  uri: dev-registry.default.svc.cluster.local:5000
  catalogType: OCIDistribution
  scanInterval: 1h
  repositories:
    - name: nginx
      matchConditions:
        - name: tags greater than v1.12.0
          expression: "semver(tag, true).isGreaterThan(semver('v1.12.0', true))"
  platforms:
    - arch: "amd64"
      os: "linux"
