# Default values for sbombastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/controller
    tag: v0.1.0-alpha1
    pullPolicy: IfNotPresent
  replicas: 3

storage:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/storage
    tag: v0.1.0-alpha1
    pullPolicy: IfNotPresent
  replicas: 1

worker:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/worker
    tag: v0.1.0-alpha1
    pullPolicy: IfNotPresent
  replicas: 3

persistence:
  enabled: true

  ## Specify a PVC for the storage data
  storageData:
    enabled: true
    subPath:
    annotations: {}
    labels: {}
    storageClass: standard
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    accessMode: ReadWriteOnce
    size: 1Gi