# Default values for sbombastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/controller
    tag: v0.1.0-alpha1
    pullPolicy: IfNotPresent
  replicas: 3

storage:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/storage
    tag: v0.1.0-alpha1
    pullPolicy: IfNotPresent
  replicas: 3
  pvc:
    name: sqlite-pvc
    requestStorage: 1Gi
    accessModes:
      - ReadWriteMany
  storageClass:
    name: sqlite-storageclass
    provisioner: kubernetes.io/no-provisioner
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer

worker:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/worker
    tag: v0.1.0-alpha1
    pullPolicy: IfNotPresent
  replicas: 3
