name: Create a new release for SBOMscanner stack

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      packages: write # Pushing images to ghcr.io
      id-token: write # Signing images with cosign
    uses: ./.github/workflows/container-build.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit
  create-release:
    needs: [build]
    permissions:
      contents: write # Creating a release
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve tag name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo TAG_NAME=$(echo ${{ github.ref_name }}) >> $GITHUB_ENV
      - name: Get release ID from the release created by release drafter
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            let releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo,
            });
            for (const release of releases.data) {
              if (release.draft) {
                      core.info(release)
                      core.exportVariable('RELEASE_ID', release.id)
                      return
              }
            }
            core.setFailed(`Draft release not found`)
      - name: Download attestation artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: attestation-SBOMscanner-*
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload release assets
        id: upload_release_assets
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            let fs = require('fs');
            let path = require('path');
            let files = [
                'SBOMscanner-controller-attestation-amd64-provenance.intoto.jsonl',
                'SBOMscanner-controller-attestation-amd64-provenance.intoto.jsonl.bundle.sigstore',
                'SBOMscanner-controller-attestation-arm64-provenance.intoto.jsonl',
                'SBOMscanner-controller-attestation-arm64-provenance.intoto.jsonl.bundle.sigstore',
                'SBOMscanner-controller-attestation-amd64-sbom.json',
                'SBOMscanner-controller-attestation-amd64-sbom.json.bundle.sigstore',
                'SBOMscanner-controller-attestation-arm64-sbom.json',
                'SBOMscanner-controller-attestation-arm64-sbom.json.bundle.sigstore',

                'SBOMscanner-worker-attestation-amd64-provenance.intoto.jsonl',
                'SBOMscanner-worker-attestation-amd64-provenance.intoto.jsonl.bundle.sigstore',
                'SBOMscanner-worker-attestation-arm64-provenance.intoto.jsonl',
                'SBOMscanner-worker-attestation-arm64-provenance.intoto.jsonl.bundle.sigstore',
                'SBOMscanner-worker-attestation-amd64-sbom.json',
                'SBOMscanner-worker-attestation-amd64-sbom.json.bundle.sigstore',
                'SBOMscanner-worker-attestation-arm64-sbom.json',
                'SBOMscanner-worker-attestation-arm64-sbom.json.bundle.sigstore',

                'SBOMscanner-storage-attestation-amd64-provenance.intoto.jsonl',
                'SBOMscanner-storage-attestation-amd64-provenance.intoto.jsonl.bundle.sigstore',
                'SBOMscanner-storage-attestation-arm64-provenance.intoto.jsonl',
                'SBOMscanner-storage-attestation-arm64-provenance.intoto.jsonl.bundle.sigstore',
                'SBOMscanner-storage-attestation-amd64-sbom.json',
                'SBOMscanner-storage-attestation-amd64-sbom.json.bundle.sigstore',
                'SBOMscanner-storage-attestation-arm64-sbom.json',
                'SBOMscanner-storage-attestation-arm64-sbom.json.bundle.sigstore',
                ]
            const {RELEASE_ID} = process.env
            for (const file of files) {
              let file_data = fs.readFileSync(file);
              let response = await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: `${RELEASE_ID}`,
                name: path.basename(file),
                data: file_data,
              });
            }
      - name: Publish release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const {RELEASE_ID} = process.env
            const {TAG_NAME} = process.env
            isPreRelease = ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: `${RELEASE_ID}`,
              draft: false,
              tag_name: `${TAG_NAME}`,
              name: `SBOMscanner ${TAG_NAME}`,
              prerelease: isPreRelease,
              make_latest: !isPreRelease
            });

  update-charts:
    needs: [create-release]
    uses: ./.github/workflows/update-charts.yml
    permissions:
      contents: write # for updatecli to update the repository
      pull-requests: write # for updatecli to create a PR
    secrets: inherit
